language: node_js 
node_js:
  - 12 
cache:
  directories:
  - node_modules 
script:
  - npm run build 
  - npm run export 
  - touch out/.nojekyll 
deploy:
  provider: pages 
  skip_cleanup: true 
  github_token: $7fdae502b53ff383929152f8f96160cd727599dc
  local_dir: out 
  on:
    branch: master